server:
  port: 8080

logging:
  config: classpath:logback/logback-spring.xml
        
spring:
  # Default Profile
  profiles:
    active: local

  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 10MB